import { app, ipcMain } from 'electron'
import fs from 'fs'
import path from 'path'
import {
  IPC_CHANNELS,
  type CookieFormat,
  type CookieReadResult,
  type CookieRecord,
  type CookieWriteResult
} from '../../shared/types'
import { ProfileRepository } from '../repositories/profileRepo'

const profileRepo = new ProfileRepository()

function getCookieFilePath(profileId: string, format: CookieFormat): string {
  const cookieDir = path.join(app.getPath('userData'), 'profiles', profileId, 'cookies')
  if (!fs.existsSync(cookieDir)) {
    fs.mkdirSync(cookieDir, { recursive: true })
  }

  const fileName = format === 'json' ? 'cookies.json' : 'cookies.txt'
  return path.join(cookieDir, fileName)
}

function normalizeCookie(input: Partial<CookieRecord>): CookieRecord {
  return {
    domain: String(input.domain ?? ''),
    name: String(input.name ?? ''),
    value: String(input.value ?? ''),
    path: String(input.path ?? '/'),
    expires: Number.isFinite(input.expires) ? Number(input.expires) : 0,
    secure: Boolean(input.secure),
    httpOnly: Boolean(input.httpOnly),
    sameSite:
      input.sameSite === 'Strict' || input.sameSite === 'Lax' || input.sameSite === 'None'
        ? input.sameSite
        : undefined
  }
}

function parseJsonCookies(content: string): CookieRecord[] {
  const parsed = JSON.parse(content) as unknown
  if (!Array.isArray(parsed)) {
    throw new Error('JSON cookies must be an array.')
  }

  return parsed
    .map((entry) => normalizeCookie((entry as Partial<CookieRecord>) ?? {}))
    .filter((cookie) => cookie.domain && cookie.name)
}

function parseNetscapeCookies(content: string): CookieRecord[] {
  const lines = content
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith('#'))

  const cookies: CookieRecord[] = []
  for (const line of lines) {
    const parts = line.split('\t')
    if (parts.length < 7) {
      continue
    }

    const [domain, , cookiePath, secure, expires, name, ...valueParts] = parts
    cookies.push(
      normalizeCookie({
        domain,
        path: cookiePath || '/',
        secure: secure.toUpperCase() === 'TRUE',
        expires: Number.parseInt(expires, 10) || 0,
        name,
        value: valueParts.join('\t')
      })
    )
  }

  return cookies.filter((cookie) => cookie.domain && cookie.name)
}

function serializeJsonCookies(cookies: CookieRecord[]): string {
  return JSON.stringify(cookies, null, 2)
}

function serializeNetscapeCookies(cookies: CookieRecord[]): string {
  const header = '# Netscape HTTP Cookie File\n# This file was generated by Multi-Profile Browser Manager\n'
  const lines = cookies.map((cookie) => {
    const includeSubdomains = cookie.domain.startsWith('.') ? 'TRUE' : 'FALSE'
    const secure = cookie.secure ? 'TRUE' : 'FALSE'
    return [
      cookie.domain,
      includeSubdomains,
      cookie.path || '/',
      secure,
      String(cookie.expires || 0),
      cookie.name,
      cookie.value
    ].join('\t')
  })

  return `${header}${lines.join('\n')}\n`
}

function parseCookies(content: string, format: CookieFormat): CookieRecord[] {
  if (!content.trim()) {
    return []
  }

  return format === 'json' ? parseJsonCookies(content) : parseNetscapeCookies(content)
}

function serializeCookies(cookies: CookieRecord[], format: CookieFormat): string {
  return format === 'json' ? serializeJsonCookies(cookies) : serializeNetscapeCookies(cookies)
}

function ensureProfileExists(profileId: string): void {
  const profile = profileRepo.getById(profileId)
  if (!profile) {
    throw new Error(`Profile not found: ${profileId}`)
  }
}

export function setupCookieHandlers(): void {
  ipcMain.handle(IPC_CHANNELS.COOKIES_READ, async (_event, profileId: string, format: CookieFormat): Promise<CookieReadResult> => {
    try {
      ensureProfileExists(profileId)
      const filePath = getCookieFilePath(profileId, format)
      if (!fs.existsSync(filePath)) {
        return { success: true, format, cookies: [], content: '' }
      }

      const content = fs.readFileSync(filePath, 'utf8')
      const cookies = parseCookies(content, format)
      return { success: true, format, cookies, content }
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error)
      return { success: false, format, cookies: [], content: '', error: message }
    }
  })

  ipcMain.handle(
    IPC_CHANNELS.COOKIES_WRITE,
    async (_event, profileId: string, format: CookieFormat, content: string): Promise<CookieWriteResult> => {
      try {
        ensureProfileExists(profileId)
        const cookies = parseCookies(content, format)
        const serialized = serializeCookies(cookies, format)
        const filePath = getCookieFilePath(profileId, format)
        fs.writeFileSync(filePath, serialized, 'utf8')
        return { success: true, count: cookies.length }
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error)
        return { success: false, count: 0, error: message }
      }
    }
  )

  ipcMain.handle(IPC_CHANNELS.COOKIES_CLEAR, async (_event, profileId: string): Promise<CookieWriteResult> => {
    try {
      ensureProfileExists(profileId)
      for (const format of ['json', 'netscape'] as const) {
        const filePath = getCookieFilePath(profileId, format)
        if (fs.existsSync(filePath)) {
          fs.unlinkSync(filePath)
        }
      }
      return { success: true, count: 0 }
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error)
      return { success: false, count: 0, error: message }
    }
  })
}
